base_index:
  path: /
  controller: App\Controller\BaseController::index

base_about:
  path: /about
  controller: App\Controller\BaseController::about

base_services:
  path: /services
  controller: App\Controller\BaseController::services